// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm9ILsVwuElSQ8ZZxg1yZh-eegROrnykU',
    appId: '1:921914971048:web:37fe37bcde7c327206039d',
    messagingSenderId: '921914971048',
    projectId: 'fir-001-87761',
    authDomain: 'fir-001-87761.firebaseapp.com',
    storageBucket: 'fir-001-87761.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkW15sEoOcuJmok7tWYnv9MTUOhKo-OOM',
    appId: '1:921914971048:android:3bc650dedf8426e706039d',
    messagingSenderId: '921914971048',
    projectId: 'fir-001-87761',
    storageBucket: 'fir-001-87761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6QRhk8YkLwkeAVzbB4sDaabhjC6GGkD8',
    appId: '1:921914971048:ios:8d2f79550727be1a06039d',
    messagingSenderId: '921914971048',
    projectId: 'fir-001-87761',
    storageBucket: 'fir-001-87761.firebasestorage.app',
    iosBundleId: 'com.example.kelimeoyunu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6QRhk8YkLwkeAVzbB4sDaabhjC6GGkD8',
    appId: '1:921914971048:ios:8d2f79550727be1a06039d',
    messagingSenderId: '921914971048',
    projectId: 'fir-001-87761',
    storageBucket: 'fir-001-87761.firebasestorage.app',
    iosBundleId: 'com.example.kelimeoyunu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm9ILsVwuElSQ8ZZxg1yZh-eegROrnykU',
    appId: '1:921914971048:web:3b5861aec3b3a57b06039d',
    messagingSenderId: '921914971048',
    projectId: 'fir-001-87761',
    authDomain: 'fir-001-87761.firebaseapp.com',
    storageBucket: 'fir-001-87761.firebasestorage.app',
  );
}
